version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    networks:
      - my_network

  wishlist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wishlist_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://sa:12345@mongodb:27017/
      MONGODB_DATABASE: wishlist
    networks:
      - my_network

networks:
  my_network:
